project_id = "vxidpkrsfqyjwwdbvtwc"

[functions.admin-users]
verify_jwt = false

[functions.create-armazem-user]
verify_jwt = false

[functions.create-customer-user]
verify_jwt = false

[functions.create-representante-user]
verify_jwt = false

[functions.safe-upload-documento]
verify_jwt = true

[functions.safe-upload-foto]
verify_jwt = true
